### ISSUE TITLE
bug report: NoSuchElementException

### ISSUE THREAD

**Issue by slimtom95** [ishare20/cnkidownloader#4]
Greetings.

An exception occurred when try to download one chapter of a book, details down here.

target_url:
```
http://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CYFD&filename=N2017120231000039&dbname=CYFDLM
```
terminal log(linux distribution):
```
请输入网址：http://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CYFD&filename=N2017120231000039&dbname=CYFDLM

第二部分 中华人民共和国行政区划名录和行政区划代码
Exception in thread "main" java.util.NoSuchElementException: No value present
	at java.base/java.util.OptionalLong.getAsLong(Unknown Source)
	at cnkidownloader/cn.lemontree.cnkidownloader.MainApp.donwnload(Unknown Source)
	at cnkidownloader/cn.lemontree.cnkidownloader.MainApp.main(Unknown Source)

```
Look forward to see your comment, great software by the way

**Comment by ishare20** [comment]
这个文献不支持下载，1.0版本没没处理这种情况所以会这样，最新版1.1修复了，但是Linux平台的没更新
